source 'https://supermarket.getchef.com'

cookbook 'git'
cookbook 'python'
cookbook 'apache2'
cookbook 'mysql'
cookbook 'openssl'
cookbook 'php'
cookbook 'php-mcrypt'
cookbook 'php-redis'
cookbook 'yum-epel'
cookbook 'redisio'
cookbook 'memcached'
cookbook 'zip'
cookbook 'hhvm'
# cookbook 'varnish'